### PR TITLE
Fixed E1743 dimming up/down regex

### PR DESCRIPTION
**Pull request by elephantmetropolis**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

This PR fixes a known regex problem involved in dimming up/down. Without the fix the value of the light brightness keep increasing/decreasing until light turn totally on/off. It also yields hundreds of events and add some lag to the lamp.

## Checklist\*

- [x] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [x] I properly tested proposed changes on my system and confirm that they are working as expected.
- [x] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by LewisSpring** [comment]
Hi @elephantmetropolis 
Thanks for your pull request.
Can you confirm that the blueprint works by adding the following URLS as blueprints?:
[raw.githubusercontent.com/lsismeiro/awesome-ha-blueprints/be6ba9333b14cdb1e296be0e3935b4af5e6976bb/blueprints/controllers/ikea_e1743/ikea_e1743.yaml](https://raw.githubusercontent.com/lsismeiro/awesome-ha-blueprints/be6ba9333b14cdb1e296be0e3935b4af5e6976bb/blueprints/controllers/ikea_e1743/ikea_e1743.yaml)
[raw.githubusercontent.com/lsismeiro/awesome-ha-blueprints/be6ba9333b14cdb1e296be0e3935b4af5e6976bb/blueprints/controllers/ikea_e1812/ikea_e1812.yaml](https://raw.githubusercontent.com/lsismeiro/awesome-ha-blueprints/be6ba9333b14cdb1e296be0e3935b4af5e6976bb/blueprints/controllers/ikea_e1812/ikea_e1812.yaml)

Other than that, looks good and should be able to merge these for you.

**Comment by elephantmetropolis** [comment]
Looks good to me !

**Comment by LewisSpring** [comment]
Great. Will merge for you
Don't forget to update your blueprints (again, sorry!) to point to the repository :)

**Comment by timcreatedit** [comment]
Hey, thanks for the great work! For my E1743 buttons, the long press still doesn't work with this, what could I be doing wrong?

**Comment by LewisSpring** [comment]
Hi Tim

I don't have this remote so unfortunately can't test for you. 
Maybe @elephantmetropolis can provide some insight if possible, :)

Can you confirm whether the actions from the remote and the blueprint are matching?

@lsismeiro If possible could you enable issues, and I will turn this into one?

Cheers :)

**Comment by lsismeiro** [comment]
Hi @LewisSpring,

I think I managed to enable issues, please check.

Regards,
Luis Sismeiro

**Pull request merged**
