### PR TITLE
Add Clamping of Color Temperature to Light Blueprint

### PR DESCRIPTION
**Pull request by botastic**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

In its current version the light hook allows the color temperature to be changed to values that are not support by the light bulbs. Reaching values far outside this range will require the user to press the opposite button, potentially overshooting in the other direction.

I added a clamping mechanism similar to the brightness minimum and maximum. Additionally, I added a feature toggle that is deactivated by default, in order to prevent any breaking changes.

I had a look at a couple of example light bulbs, here are their valid color temperature ranges:
- [Innr RB 279 T](https://www.zigbee2mqtt.io/devices/RB_279_T.html): [153, 555]
- [Philips 9290022169] (https://www.zigbee2mqtt.io/devices/9290022169.html): [150, 500]
- [LEDVANCE AC25704](https://www.zigbee2mqtt.io/devices/AC25704.html): [150, 500]

## Checklist\*

- [x] I followed sections of the [Contribution Guidelines](https://github.com/lsismeiro/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [x] I properly tested proposed changes on my system and confirm that they are working as expected.
- [ ] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

NOTE: I did not commit the result of formatting, because it changed quit a lot of files. Either my formatting is not setup correctly or the code has not been formatted recently. However, none of my changes were changed by formatting :)

### CODE REVIEW

**Comment by LewisSpring** [comment]
Hi, sorry I forgot about this!

Don't worry about the formatting, I don't bother with it for the same reason. 

Let me test this and I'll merge if all good.

**Comment by LewisSpring** [comment]
Looks good to me, I'm happy to merge but wanted to check you tested this long term with no issues?

**Comment by botastic** [comment]
Hey, no worries, I was also a bit busy.

I have my fork running since I created the PR and I'm using the feature with the [Innr RB 279 T](https://www.zigbee2mqtt.io/devices/RB_279_T.html) bulbs together with an [IKEA E1810](https://www.zigbee2mqtt.io/devices/E1524_E1810.html) - no issues so far. I also checked the clamping once more and it is still working.

Also thank you very much for maintaining this fork and being open to PRs!

**Comment by LewisSpring** [comment]
Thanks!
Merged. Will send out a message to the Redux threads when I get a moment

**Pull request merged**
