### PR TITLE
fix: e1810 up and down long press events with zha

### PR DESCRIPTION
**Pull request by l3d00m**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

For my two  e1810 Ikea remote, the long press events for the up and down button were not working. I had to change the codes to the following, it works now. I'm not sure how it will effect the other model (e1524)

## Checklist\*

- [x] I followed sections of the [Contribution Guidelines](https://github.com/lsismeiro/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [x] I properly tested proposed changes on my system and confirm that they are working as expected.
- [ ] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by LewisSpring** [comment]
Thanks for your pull.

I think it would be best to merge it for now and separate the controllers if needed.

**Comment by danhemsoe** [comment]
Hi..  
I have an e1524 remote, and this change break the long press up/down. If I revert the changes it works again. So is it possible to have different values depending on which remote is used in this blueprint?

/Dan

**Comment by LewisSpring** [comment]
> Hi.. I have an e1524 remote, and this change break the long press up/down. If I revert the changes it works again. So is it possible to have different values depending on which remote is used in this blueprint?
> 
> /Dan

Hi Dan.
Sorry about that.

@yarafie - could i ask you a favour?
Could you update the e1524/e1810 blueprint in your repo (for the v2 pull) to have a device selector like e2001/e2002 to resolve this?

**Comment by yarafie** [comment]
@lsismeiro I thought I did.
See below

 ```
33     controller_device:
 34       name: (deCONZ, ZHA, Zigbee2MQTT_V2) Controller Device
 35       description: The controller device to use for the automation
 36       default: ''
 37       selector:
 38         device:
 39           filter:
 40           - integration: mqtt
 41             manufacturer: IKEA
 42             model: TRADFRI remote control (E1524/E1810)     <-----------------
 43           - integration: zha
 44             manufacturer: IKEA of Sweden
 45             model: TRADFRI remote control
 46           - integration: deconz
 47             manufacturer: IKEA of Sweden
 48             model: TRADFRI remote control
 49           multiple: false

```

**Comment by yarafie** [comment]
@danhemsoe @lsismeiro 

No guarantees but

Try changing the 2 lines below

Line 346 
from
button_up_long: [move_with_on_off_MoveMode.Up_83]
to
button_up_long: [move_with_on_off_MoveMode.Up_83, move_with_on_off_MoveMode.Up_84]

Line 349
from
button_down_long: [move_MoveMode.Down_83]
to
button_down_long: [move_MoveMode.Down_83, move_MoveMode.Down_84]

**Pull request merged**
