### PR TITLE
Added Support for IKEA RODRET wireless dimmer/power switch (E2201)

### PR DESCRIPTION
**Pull request by yarafie**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Breaking change
This may  break existing automations based on the older version for ikea Tradfri e1743 if being used.

A redownload/update/resetup of the ikea_1743.yaml will probably be needed.

To use the new Ikea Rodret e2201 controller a redownload/update/resetup of the hooks will also be needed.

## Proposed change\*

Added Support for IKEA RODRET wireless dimmer/power switch (E2201)
as a controller and added it to the relevant hooks. The controller should now work with the upcomming release of zigbee2mqtt 2.0.0 as triggeres were refactored to use mqtt rather than the depecrated sensor.\<DEVICE\>_action.

Additionaly Updated IKEA E1743 TRÅDFRI On/Off Switch & Dimmer controller also to use mqtt triggers.

## Checklist\*

- [ Y] I followed sections of the [Contribution Guidelines](https://github.com/lsismeiro/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ Y] I properly tested proposed changes on my system and confirm that they are working as expected.
- [ Y] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by LewisSpring** [comment]
Thanks for your pull! - Very appreciated.

I promise this is not a nit pick, but would you be able to redo the edits you made using a basic text editor from the source file?
Something - i presume HA? - has fiddled with the formatting a bit adding { and } and new line breaks and therefore your new changes aren't clear for other people to draw from.

It would help myself understand the new method as well :)   - hopefully it is fairly drop-in and can be replicated across the blueprints.

Cheers :)

**Comment by yarafie** [comment]
> Thanks for your pull! - Very appreciated.
> 
> I promise this is not a nit pick, but would you be able to redo the edits you made using a basic text editor from the source file? Something - i presume HA? - has fiddled with the formatting a bit adding { and } and new line breaks and therefore your new changes aren't clear for other people to draw from.
> 
> It would help myself understand the new method as well :) - hopefully it is fairly drop-in and can be replicated across the blueprints.
> 
> Cheers :)

Dang. I just looked at the pull request files changed and looks like something really mucked up the formatting.

I might just do a complete new git clone and redo the changes on the original version.
I am actually doing this on my phone logged into my Linux server through a terminal session. All command line stuff no GUI's :)

**Comment by LewisSpring** [comment]
> > Thanks for your pull! - Very appreciated.
> > I promise this is not a nit pick, but would you be able to redo the edits you made using a basic text editor from the source file? Something - i presume HA? - has fiddled with the formatting a bit adding { and } and new line breaks and therefore your new changes aren't clear for other people to draw from.
> > It would help myself understand the new method as well :) - hopefully it is fairly drop-in and can be replicated across the blueprints.
> > Cheers :)
> 
> Dang. I just looked at the pull request files changed and looks like something really mucked up the formatting.
> 
> I might just do a complete new git clone and redo the changes on the original version. I am actually doing this on my phone logged into my Linux server through a terminal session. All command line stuff no GUI's :)

That's odd then! I wouldn't expect most CLI utils to do anything like that!

I appreciate you looking into that.

**Comment by yarafie** [comment]
> > > Thanks for your pull! - Very appreciated.
> > > I promise this is not a nit pick, but would you be able to redo the edits you made using a basic text editor from the source file? Something - i presume HA? - has fiddled with the formatting a bit adding { and } and new line breaks and therefore your new changes aren't clear for other people to draw from.
> > > It would help myself understand the new method as well :) - hopefully it is fairly drop-in and can be replicated across the blueprints.
> > > Cheers :)
> > 
> > 
> > Dang. I just looked at the pull request files changed and looks like something really mucked up the formatting.
> > I might just do a complete new git clone and redo the changes on the original version. I am actually doing this on my phone logged into my Linux server through a terminal session. All command line stuff no GUI's :)
> 
> That's odd then! I wouldn't expect most CLI utils to do anything like that!
> 
> I appreciate you looking into that.

What I'll do ths time round is leave the original code but comment it out with
#CHANGED - YAR
with the changed code below it.
That way you can go right down to the code that was changed and see both rather than just rely on a diff.

**Comment by yarafie** [comment]
Cancelling current pull request will create a new one

**Pull request closed without merging**
